### ISSUE TITLE
Group chat

### ISSUE THREAD

**Issue by abika** [kontalk/desktopclient-java#1]
See kontalk/androidclient#179 and kontalk/tigase-extension#5.
The basic data model and GUI support this but the real implementation depends on the decisions for the "Kontalk vs. XMPP" protocol specifications.

Can't do anything right now.

**Comment by abika** [comment]
can we clarify some points again?:
* What should be handled by the server?  
I would say: nothing, right now. We only need to keep in mind that this can be changed in the future: The server gets one message and forwards it to each group member, encrypted individually
* What protocol specifications do we need?  
Constraints: simple and fail-save. The worst that can happen is that after everything is specified and implemented, this one unthinkable use-case pop ups that breaks everything
  * group ID: A must. A global unique identifier with no further derived meaning - like the message or thread ID
  * adding all participants to each message?  
**PRO:** reduced protocol, membership information unambiguous for every participant (and the server later)  
**CONTRA:** overhead in terms of message size and message parsing (suitable with 50+ participants?). Shannon would kill us :~
  * and connected to this: required protocol commands?  
<code>create</code> (maybe),
<code>delete</code> (no),
<code>add (member)</code> (depends on above),
<code>remove (member)</code> (depends on above),
advanced:
<code>subject</code>,
<code>admin</code>

Together with the usage public/subscriber and blocking specs I still get a headache here. But as long as we keep it simple and consider the group-chat extension only as the interpretation of ``` this message was also sended to... ``` we should be on the safe side (eh, right?).

**Comment by daniele-athome** [comment]
> The server gets one message and forwards it to each group member, encrypted individually

Just a note on this: to support encryption, we could use an approach similar to what OpenPGP does: encrypt the message with a symmetric key and then send that key encrypted multiple times (one for each user in the group) with the users' public keys.

This key could be generated by the groups's creator and then sent to all participants (encrypted with each one's public key of course). This new key will be used by the participants to encrypt messages for the group and certify that they are part of the group. This could be used as some sort of an "invitation system" (of course this would mean anyone can invite anyone, but that's fine).

> group ID: A must. A global unique identifier with no further derived meaning - like the message or thread ID

We could use an hash of the group public key I described above, but that's just a hint anyway.

> adding a list with all participants to each message?

Yes, Shannon will certainly kill us. I don't have other ideas though.
However, by using a shared group key, we'll avoid encrypting the message multiple times for every user (which will increase its size even more).

What do you think?

**Comment by abika** [comment]
> Just a note on this: to support encryption, we could use an approach similar to what OpenPGP does: encrypt the message with a symmetric key and then send that key encrypted multiple times (one for each user in the group) with the users' public keys.

again some bullet points (correct me if I'm wrong somewhere):
* this is was the guys from TextSecure are [describing](https://whispersystems.org/blog/private-groups/) as *even further* optimization, without implementing it
* it does not involve the server at any point which is a *yeah*
* and now imo a big mistake:

> This could be used as some sort of an "invitation system" (of course this would mean anyone can invite anyone, but that's fine)

really? There is good reason why other messengers have an admin role here (unfortunately friendship is not transitive). This can also lead to membership conflicts/ambiguity, headache again.
We should only let the creator allow to handle membership administration, and not derive anything from somebody having the group key.

* adding a list with all participants to each message?
Why are dedicated add/remove commands not an option? (just asking, still unsure)

**Comment by daniele-athome** [comment]
> adding a list with all participants to each message? Why are dedicated add/remove commands not an option? (just asking, still unsure)

Because it would make it just like MUC, wouldn't it? A single server will be responsible for hosting a group, with all its rules (members, admin role, etc.). Unless I'm not fully getting your point.
Isn't add/remove/other_command handled by the server? Unless you want them to be handled by the group creator client, am I getting this right?

**Comment by abika** [comment]
> Unless you want them to be handled by the group creator client
That's what I mean. Server is not involved, the group creator sends add/remove/... messages to all participants.

**Comment by daniele-athome** [comment]
Oh I see. Sorry I wasn't getting that :-)
What about authorization? I mean anyone could send add/remove commands at their will, right?

**Comment by abika** [comment]
> I mean anyone could send add/remove commands at their will, right?

Yes, but clients should ignore commands not coming from the group creator (we HAVE to rely on the clients, when the server is not handling this). Already discussed [above](https://github.com/kontalk/desktopclient-java/issues/1#issuecomment-53633688)

**Comment by daniele-athome** [comment]
Ok then, I will write a wiki page soon with a protocol draft. Let's see if I got it right:

* message extension: `<group>` with an ID to every message
* add/remove commands sent by the admin to all participants, sent as messages (body will include a description displayed by incompatible clients)
* create command (initial create-and-join command)
* part command (leave group; an announcement to all other users that I'm leaving the group)
* since messages are sent individually to each member by each clients, using a shared key doesn't really make sense anymore, does it?

Of course clients supporting this protocol will advertise it through service discovery.

Only thing that fits wrong with this approach is blocking support. Blocking is for JIDs, and JIDs are entities supported and handled by a server. If group chat is handled fully by clients, no JID entity would exist that represents a group. Unless we implement block group feature as "ignore and discard messages from this group". What do you think?

**Comment by abika** [comment]
> since messages are sent individually to each member by each clients, using a shared key doesn't really make sense anymore, does it?

No, currently not. But the server could be extended with an (independent?) protocol, so that it gets a list of addresses, one (encrypted) message and simply distributes it.

Everything else looks fine by me.

> Unless we implement block group feature as "ignore and discard messages from this group". What do you think?

I would say special blocking of groups is not required. Other messengers don't have/need that, and the current blocking is sufficient: If you don't want get normal messages from another user, you usually also don't  wanna get group invitations.

Of course, we need to take care of the case if the group creator or group members are blocked. But the clients should be able to handle that themselves.

**Comment by daniele-athome** [comment]
> No, currently not. But the server could be extended with an (independent?) protocol, so that it gets a list of addresses, one (encrypted) message and simply distributes it.

Well, shared secrets are always dangerous in one way or another, so if clients have the power here, let's encrypt every message with only the recipient's key.

I'll draft something as soon as I can.

**Comment by abika** [comment]
huh? Wasn't it your idea to use a shared symmetric key? If the group creator initially sends it to all members, all senders can send only their one message (together with the list of recipients/group members) -> great traffic reduction.

But anyway, not that important right now

**Comment by daniele-athome** [comment]
Sorry, yes actually that comes naturally with OpenPGP encryption (when encrypting to multiple recipients that's exactly what GnuPG does). I was confusing it with something else, never mind :-)

**Comment by daniele-athome** [comment]
I put down some words about the protocol in a wiki page, absolutely in a very draft status:
https://github.com/kontalk/specs/wiki/Group-chat

I'm a little uncertain about the *add user* command:

> (The group creator|Anyone) can add users by sending a group command:

What if the group creator leaves the group? Does the group become orphan?
Also, are we granting the group creator ban privileges?

**Comment by Manizuca** [comment]
Hi, after reading the discussion i ended with this image of the implementation, maybe i added my own ideas :)

* Alicia creates a group chat  with Bob and Catalina, the client sends creates a group ID and a symetric key, then sends the invitations with the ID to Bob and Catalina. They can accept or reject. Blocking the admin will block the group, as the invitation wouldn't be received
  * The admin will have a pending-invitations list, he should be able to cancel pending-invitations in the members-list. There need to be a invitation time limit
* When someone accept, he will be added to a members-list and the key is sent with the ID and the list as a personal-message. When the second one accepts the message with the key, the ID and the new list will be sent to him as a personal-message, and the change in the list will be sent by the admin to previous member as a group-message, the group-messages will be signed with the symetric key
  * Options for participants list:
    * The group-messages have a field with the list of receivers, the server send the message to everyone in the list. The participants list is managed by the admin. This can help to also implement kontalk/androidclient#105 (the broadcast will have a list of receivers, and will be signed with the private key of the sender)
    * The server has a list of participants, when there is a change in the list, its informed as a group message to everyone, and also to the server
* Bob accepts the invitation and then sends a message to the group.
* Catalina accepts the invitation, and she doesn't receive any message
* Bob gets offline, and tries to send a new message
* Alicia adds Daniel and Eva to the group, when they accept he send the change to everywhere as a group-message (and to the server if it has the list), and to Daniel and Eva as personal messages with the key
* Bob gets online, he must check for a change in the members-list before trying again to send the message
* Catalina gets offline, she tries to send a 20MiB video (assuming that it would be possible in the future to send big files encrypted)
* Alicia removes Eva and Bob from the group. She sends a message to both at once with the notification, and send the changes in the list as a group-message to every one left in the group
  * She should be able to delete multiple users at once, to avoid recreating the key multiple times.
  * Eva and bob had the group key, so if they can intercept messages they still can decrypt them. So alicia creates a new key and send it as a personal-message to everyone left in the group.
* Catalina gets online and receives the new key and members-list, then tries again to send the video
  * I dont know if encrypting big files its something that takes to much resources, maybe we can avoid re-encrypting the video with the new key. For this Catalina should check if the message is bigger than some threshole, if is bigger she should use a message extension and add tho the message the old-key encrypted with her private key and the new-key.
  * What needs to happen if the list is included with the message and there is a new/removed member when uploading the video?
* All the participants should keep the old key until checking for missing messages and decrypting all of them
* There must be a time limit of time, e.g. if a user never clicks the "download" option in a image, after the limit the old key would be deleted and the download optiod disabled (I also assume the fileserver has a time limit for things like images)
  * Im not sure how actually works if a user recreates his key, he just doesn't receive all the missing messages encypted before the change?
* If someone leaves a group, he send a group-message with a notification about the change 
  * When the admin receives the change, he creates a new key and send it as personal-messages
* The admin can change the admin of the group by sending a group-message with the changes.
  * The admin can only make the change if is connected, to prevent trying to set a non-member as admin
  * Someone can only leave the group if is connected, to prevent leaving it being admin
  * When the admin leaves the group, he should be asked for the new admin.

Maybe instead of recreating the key with every participant removed, the admin could have the option to manually recreate in and/or it will be recreated after 5 participants removed (with information about when was created the key)

My question is how would this work with using multiple clients, here can help kontalk/androidclient#250, so the other client know the changes. But if the message was missed (timeouted), there should be some information in the roster that includes a timestamp of the key and participants-list... if the timestamp is different the client can request the key to the admin and himself (if is connected in the other client)

And how should this work when using kontalk and a client that doesnt support this?, i suppose that the server will just send the messages to the client with support, so kontalk don't misses the messages

**Comment by daniele-athome** [comment]
Thanks @Manizuca for your protocol review. However there are a few things that are not allowed.

* servers don't store any information about groups
* the key is renewed at every message. As of OpenPGP standard, a new symmetric key is created with every message and it's used to encrypt it. The symmetric key is then encrypted for every user using their public keys and attached to the encrypted message
* making group chat permissions based solely on encryption makes the protocol incompatible with non-encrypted clients. Encryption should be something on top of the protocol

**Comment by Manizuca** [comment]
> the key is renewed at every message. As of OpenPGP standard, a new symmetric key is created with every message and it's used to encrypt it. The symmetric key is then encrypted for every user using their public keys and attached to the encrypted message

With big groups there can be a big overhead in the message size, there is no way that the same key can be used with multiple messages without being incompatible with the standard? (I'm not familiar with OpenPGP) E.g. it can be renewed every 10 messages?, or can the key be used for messages in the next 4 hours? (In that case can be a problem if the message with the key arrives later)
If is not possible then the groups need to have a limit of participants

**Comment by abika** [comment]
[Finally have some time, sorry for delay].

> All messages are multicasted to the other participants through XEP-0033.

Hmm, at first I thought this a really great idea, as it reduces the custom group protocol to a minimum. But there is a problem here: Each client gets the same (unencrypted) recipient list, even it it didn't change. This means unneeded overhead and a security problem (The server needs the list, but not anybody listening between server and client). Also, removing a participant from the group should be possible, see below.

>>    (The group creator|Anyone) can add users by sending a group command:

>What if the group creator leaves the group? Does the group become orphan?
>Also, are we granting the group creator ban privileges?

I'm still thinking only the group creator should be able to do that. He/she initially created the group and  should have the privilege to decide who's in there. Yes, when the creator leaves nobody can add user, but another one can be set up easily. And a group "lives" forever anyway, as there is no way to "destroy" it.

As its only client side this surely can't be enforced. But the whole protocol can be seen only as a behaviour recommendation for the clients - which is totally fine, as long as clients can't force other clients to do unwanted things.

The creator should also be able to remove user. This gets tricky as the removed user need to get a message about this and at the same time everyone remaining in the group needs to know who was removed.

But this is a very good start. The mean idea of implementing a group (almost) only by an ID is brilliant.

@Manizuca : You're raising some good questions. But keep in mind that we need to have simple and strict rules to ensure reliability, usability and security.
* Implementation is client side, server not involved. And actions like group creation, sending messages, leaving a group should still be possible independent of any receiver/client being online or responding. This means (for example) we cant have special group invitations.
* For the same reason a group key is not a good idea. The group creator is responsible for key renewal and distribution, until then no new messages can't be exchanged.
* multiple clients/message loss: very good point, seems like sending the complete group participant list in each message is a MUST to ensure membership 	consistency(?)

**Comment by daniele-athome** [comment]
> Hmm, at first I thought this a really great idea, as it reduces the custom group protocol to a minimum. But there is a problem here: Each client gets the same (unencrypted) recipient list, even it it didn't change. This means unneeded overhead and a security problem (The server needs the list, but not anybody listening between server and receiving client). Also, removing a participant from the group should be possible, see below.

I could make the server filter that part from messages containing the group extension (that would mean leaving the `<group/>` extension unencrypted) intended to clients. We'd be slightly out of standard, but Kontalk group chat is already out of standard, so no big deal :-) Besides, it would be of great help in saving bandwidth. However, outgoing messages will always need the list of participants I'm afraid.

> The creator should also be able to remove user. This gets tricky as the removed user need to get a message about this and at the same time everyone remaining in the group needs to know who was removed.

We may do it in either two ways:

* send something like a *kick* command to the kicked user and then send a *remove" command to everyone but the excluded indicating the kicked user in the group extension
* send a *remove* command to everyone indicating the kicked user in the group extension

Any other idea?

> * multiple clients/message loss: very good point, seems like sending the complete group participant list in each message is a MUST to ensure membership consistency(?)

I completely skipped that part, sorry.
Theorically, if for example a new device registers *after* creating a group, it would have no way of knowing the participants. We could make the new device ask the old device to provide it group information... I don't know... ideas about this? Even though kontalk/androidclient#250 isn't very well defined yet.

**Comment by abika** [comment]
> I could make the server filter that part from messages containing the group extension (that would mean leaving the <group/> extension unencrypted) intended to clients. We'd be slightly out of standard, but Kontalk group chat is already out of standard, so no big deal :-) Besides, it would be of great help in saving bandwidth. However, outgoing messages will always need the list of participants I'm afraid.

Well, the problem here is we actually need two lists: One for the server to know each recipient, in plain text. And one for the recipients to know the group member, encrypted. Is it feasible to send two lists (only for management commands)?

> Any other idea?

Nope, had also these two in mind. I prefer second one: sending one message to everybody with the removed user labelled.

Another idea: How about adding the JID of the group creator(=admin/owner) to the group ID (in every message): `<group xmlns=... owner=alice@kontalk.org id='GROUP-ID'/>` 
A group is know identified by the tuple (owner,id). This will solve two problems:
* Whenever a client gets a message with an unknown group (bcause of message loss, or whatever), there is a contact entity, for requesting the group participants. And the client is sure to ask the right one.
* Group hijacking is impossible: Multiple group member can conspire to claim on of them is the owner, or one member resends the create message to claim ownership... (or other evil stuff I can't even think of).

**Comment by abika** [comment]
[ did you reply by editing my message .) ]

**Comment by daniele-athome** [comment]
Yes. I am sorry. Seriously. I was probably in a great need for rest that day. I'll fix it immediately.

**Comment by daniele-athome** [comment]
> Well, the problem here is we actually need two lists: One for the server to know each recipient, in plain text. And one for the recipients to know the group member, encrypted. Is it feasible to send two lists (only for management commands)?

Well, I guess having duplicate information has no advantage in this case, hasn't it? I mean metadata is leaked anyway because routing needs the participants list.
Of course management commands will have the JID of the involved user (for example when adding or removing) in a XML element included in the encrypted part. Unless we are talking about the same thing here?

> Nope, had also these two in mind. I prefer second one: sending one message to everybody with the removed user labelled.

Labelled as in putting it in an inner XML element in the group extension right? What about recipients? I guess also the removed user needs to know he/she is been removed.

> Another idea: How about adding the JID of the group creator(=admin/owner) to the group ID (in every message): `<group xmlns=... owner=alice@kontalk.org id='GROUP-ID'/>` 
A group is now identified by the tuple (owner,id). This will solve two problems:

Great idea, I'll add it to the draft spec. Feel free to edit the wiki page of course if you think there's something wrong.

**Comment by abika** [comment]
As you already noticed, I'm working on the group extension and group chat integration. But don't worry, nothing is considered final. In fact, a lot of different ways to implement this popped up and its the question of best practice now.

* A group command is added as attribute to the stanza as one message can only contain one operation (like the `type` attribute for many XMPP stanzas). If there is no command then the stanza is only there for identifying the group.
* Adding and removing is now combined with a `set` command. This makes it possible to add and/or remove multiple users with with one command (but I consider this only being a small advantage). 
* Related to that and more important is the problem of adding users with two possibilities:
  1. A message including the added user and a list of all other group users is sent to everybody.
  2. A message with the list of group members is only send to the new user. Everybody else gets another (smaller) message.

The trade-off: sending one/two messages **vs.** bigger/smaller payload of messages received by unchanged users.
Based on the decision here the protocol will look different.

Other issues:
* XEP-0033 doesn't mention the `id` attribute, but I guess as one sent message can only have one ID every receiver will get a message with the same ID. The ID is not really unique anymore, but there shouldn't be any major problems.
* If a received message can't be encrypted for whatever reason the client can't distinguish if the message was part of a group conversation or a single chat. Quick idea for a workaround: use the group ID also for the `thread` attribute in a message stanza.

TODO: A `subject` stanza.

[btw: I don't have rights to edit the wiki in specs]

**Comment by sim6** [comment]
Is the development of group chat in the following branch?
https://github.com/kontalk/desktopclient-java/commits/feature-group_chat

**Comment by abika** [comment]
yes, but its not finished yet. Everything will be in master when it is at least in a 'proof of concept' state.

And the protocol is not final either.

**Comment by daniele-athome** [comment]
> The trade-off: sending one/two messages vs. bigger/smaller payload of messages received by unchanged users.
Based on the decision here the protocol will look different.

First of all, thanks for your work so far.
Getting to the point: I'd be more keen to adhere to XEP-0033 and not strip the `<addresses/>` part. Although messages will be bigger, group members will always be available, even if the owner is currently offline (and therefore if a sender doesn't know the members for whatever reason, he/she must wait for the owner to come online). I feel like I'd accept such a overhead in this case. Besides, we can always improve it later in some other way (or just wait for the almighty MUC2).

> XEP-0033 doesn't mention the id attribute, but I guess as one sent message can only have one ID every receiver will get a message with the same ID. The ID is not really unique anymore, but there shouldn't be any major problems.

Indeed. Besides, having the same ID for the "same message" in a group could make sense (I mean it's the same message afterall, just broadcasted).

> If a received message can't be encrypted for whatever reason the client can't distinguish if the message was part of a group conversation or a single chat. Quick idea for a workaround: use the group ID also for the thread attribute in a message stanza.

I don't think this can be much of an issue. In 99% of cases, when you receive an encrypted messages you can't decrypt it and you're stuck with it (the sender used an old key which is already invalid/non-existant, so the message is pretty much lost). Knowing that an encrypted message is part of a group doesn't really matter.
The other 1% is when a temporary error occur in the Android client (I can't actually think of one right now, I'm just assuming the worse so I never use "100%" :-)

---

I've seen the GroupExtension code, but I'd bring some modifications:

* Since we are going to use XEP-0033 also for all messages, add and remove commands are not needed anymore (the client can see which users are new and which are gone by comparing its own list)
* Because of the same reason, we don't even need a create command anymore. We just send the first message along with the `<group/>` extension and all recipients will know about the group.
* In theory, in order to stick to the "always all information" rule, we should also include a `<subject/>` tag (child to `<group/>`) in every message. In practice: we should.
* It'd be more "XMPP/XML-way" if the command would be child to `<group/>` as a tag instead inside of a command attribute

---

Replying to your latest email:

> How to handle group members that are not in the contact list: A user that gets an
invitation for a new group chat might not know the participants at all and doesn't expect
them to be added as contact. However, this breaks (at least in the desktop client) the
model associations as requesting/accepting/saving a public key requires to have a contact
entity.

The group members are always listed in every message so this should not be a problem, if I understand you correctly.
Unknown contacts will be listed as unknown (using the hash, that's the only information available until an invitation workflow starts - which will make the users exchange their keys, where we can find the username).

> Another question is what will happen if a contact that is part of a group chat is
deleted.

That will all depend on the client UI behaviour. I'd revert back to the hash for the sake of consistency. What do you think?

---

Final note: I've been away from this discussion for a long time, doing other tasks and working on multiple things at the same time. If by any means I've skipped something or some of the stuff I said doesn't make sense at all, **please say it** :-)

**Comment by abika** [comment]
(For the sake of clarity I only respond to points where there is something important to say / that are not already obsolete).

> Getting to the point: I'd be more keen to adhere to XEP-0033 and not strip the `<addresses/>` 
part.

I have to say I don't like that.
* we are changing and misusing a standard XEP for something that it was not intended to be used for
* bigger payload for every message (but you pointed that already out yourself)

I propose using 0033 only for sending a group message (with striping) and including the member list again encrypted inside the group extension (with the downside of even bigger payload).

But if you say your design is the way to go, we can do it like that. I still can't recommend it.

Something else:
> group members will always be available, even if the owner is currently offline (and therefore if a sender doesn't know the members for whatever reason, he/she must wait for the owner to come online).

There is a problem with authorization here: The group owner is the only one who can add/remove members, right? So, member lists from other group participants can not be trusted, otherwise they will also be able to add/remove members. Therefore the group owner is the only one who can give reliable information and MUST be asked if needed.

---

> * Since we are going to use XEP-0033 also for all messages, add and remove commands are not needed anymore (the client can see which users are new and which are gone by comparing its own list)

With one exception: removing will require sending an additional message to the removed member with a `kick` command.

And it could better to exchange explicit "diffs" (add/remove) to avoid ambiguous member affiliation. (You know, clients are not always connected and there is always some latency in transmissions, if two clients send contradicting messages...)
But I'm really not sure about that myself.

> * Because of the same reason, we don't even need a create command anymore. We just send the first message along with the `<group/>` extension and all recipients will know about the group.

New group participants won't be able to tell if a group was just created or if they were added after some time. But that's not a big deal.

---
> The group members are always listed in every message so this should not be a problem, if I understand you correctly.

Well, my point is this: If a group participant is unknown to me: will it be added to the contact list like an ordinary contact? Will it also be inserted into Androids address book (although the phone number will be missing)? Can the display name be changed?

> That will all depend on the client UI behaviour. I'd revert back to the hash for the sake of consistency. What do you think?

Yes, the hashes must used. But if the contacts public key is also deleted, sending encrypted messages to the group won't be possible anymore.

But this is only about implementation design. If you found solutions for these problems, everything is fine.

**Comment by daniele-athome** [comment]
> I propose using 0033 only for sending a group message (with striping) and including the member list again encrypted inside the group extension (with the downside of even bigger payload).

It might be a good solution afterall... the biggest payload would be only for the initial message; XEP-0033 parts will be stripped out and we already have a list of members inside.

Still... I have reservations even on myself on this because I always think about saving bandwidth and energy so I am conflicted.
However, with the help and patches I've been providing to Tigase (and their continuous efforts and help too), message delivery has now reached (as far as I could have seen for the past few weeks) 100% reliability. So I guess we could save adding the members list **to every message**.
Worst case scenario, **a client reinstalling Kontalk** will receive a message about an unknown group that will have members only after the group creator has responded?
(About this specific aspect: what about asking the first sender that comes up online about group members? And then ask for confirmation to the owner as soon as it comes online? I know it seems like a silly idea, but whatever, we are brainstorming :-)

> With one exception: removing will require sending an additional message to the removed member with a kick command.

Right, thanks for pointing that out.

> And it could better to exchange explicit "diffs" (add/remove) to avoid ambiguous member affiliation. (You know, clients are not always connected and there is always some latency in transmissions, if two clients send contradicting messages...)
> But I'm really not sure about that myself.

As I said before, I am conflicted too.
It seems to me we eventually always go back to the same conclusion: having add/remove commands is better than having the members list in every message. Maybe we should really adopt these method and begin trusting server reliability (starting with myself doing it - and probably the fact that I work on the server too makes me think it's unreliable, but I mean we are using a server mainly because it's more reliable than clients, isn't it?).

> Well, my point is this: If a group participant is unknown to me: will it be added to the contact list like an ordinary contact? Will it also be inserted into Androids address book (although the phone number will be missing)? Can the display name be changed?

It will happen much like it happens now if you receive a message from an unknown contact.
If you are authorized to chat to each other, you will just see his/her username or the hash if a public key isn't available yet (which should not happen, but that's a problem for another time).
If you are not authorized to chat to each other, you will not receive group messages at all from that user - we talked about this before, we need a serious ad-hoc authorization workflow for groups - people expect that conversations in groups do not need 1-to-1 chat authorization.

> Yes, the hashes must used. But if the contacts public key is also deleted, sending encrypted messages to the group won't be possible anymore.

Currently, if you remove a contact from Android contacts, the subscription is kept alive, no unsubscription is done, so technically the key is preserved (the sync process in the Android app also looks for roster entries). You will see the username and the hash though, no phone number. But message exchanging will continue to work.

I'm moving the Group chat wiki page into the specs repository inside an md file. I will grant you commit access to that repo so we can work together on the specs.

**Comment by abika** [comment]
> So I guess we could save adding the members list **to every message**.
Worst case scenario, **a client reinstalling Kontalk** will receive a message about an unknown group that will have members only after the group creator has responded?

True, and I think this case is acceptable.

But I just realized that unless message sync between clients (kontalk/androidclient#250) is implemented having multiple clients will break group chat. Clients not connected for some time can never be sure they didn't miss group changes (and must ask the group creator for every group on every re-connect to make sure they are up-to-date).

> (About this specific aspect: what about asking the first sender that comes up online about group members? And then ask for confirmation to the owner as soon as it comes online? I know it seems like a silly idea, but whatever, we are brainstorming :-)

This will make it just more complicated. If the requested information is invalid the client could send messages to users not in the group and actual group members will miss messages. (Yes, I'm assuming the worst but it's not unlikely some script-kiddie will exploit this)

> As I said before, I am conflicted too.
It seems to me we eventually always go back to the same conclusion: having add/remove commands is better than having the members list in every message. Maybe we should really adopt these method and begin trusting server reliability (starting with myself doing it - and probably the fact that I work on the server too makes me think it's unreliable, but I mean we are using a server mainly because it's more reliable than clients, isn't it?).

If the server is not reliable there is really no way to ensure group consistency - unless the clients constantly ask for the group members (see above). And this is independent from the protocol details so we should focus the other error cases and make handling these as robust as possible.

I'll try adding the use-cases for the problems were discussing here to the specs in the next days.

**Comment by erdmark** [comment]
Instead of sending the whole member list in every message just send a hash of it.
When a member is added or removed then send the whole member list.
If somebody does not know all members ask any member or the group admin for the full list.
Because the admin sent the hash first, the hash is reliable. Now you can prove the list is correct by calculating the hash.

**Comment by daniele-athome** [comment]
Thanks @erdmark, the protocol has been recently revised to not send the members list on every message in the `<group/>` element. However, the server needs to know where to deliver the message, so [XEP-0033](http://www.xmpp.org/extensions/xep-0033.html) is used for this purpose (unfortunately there is no other way without storing state on the server).

---

https://github.com/kontalk/specs/blob/master/group.md#sending-messages

**Comment by webratte** [comment]
Is there a release date planed for Desktopclient with groupchat?

**Comment by daniele-athome** [comment]
IIRC I believe it is already fully implemented. I can't try it right now, @abika can you confirm please so we can close the issue.

**Comment by abika** [comment]
Just tested again, basic operations (create/leave/add/remove) are working between current versions of Desktop and Android client. There are issues left but I will work on them separately.

A big problem are still the lost messages due to missing message archive. A disconnected client will miss group commands making the groups inconsistent. For this reason I won't enable the creation of groups in the Desktop client, user experience will just be bad.
