### ISSUE TITLE
Changes in settings will not stored by shuting down the computer

### ISSUE THREAD

**Issue by webratte** [kontalk/desktopclient-java#68]
Clientversion 3.1
OS Lubuntu (Linux)

Steps to reproduce:
Open Settings 
Change a setting (e.g. show myself in contacts)
Click "save"
Shut down the computer without closing Kontalk

Restart the computer and check the changed setting.

If I close Kontalk from the Systray before shutting down the computer the change will be saved

**Comment by abika** [comment]
configuration is saved now immediately when you click on "save".

But this is actually a problem with your Linux environment: On shutdown(or reboot) all open programs are killed right away before they can gracefully shutdown.
Because its Linux you can easily pinpoint the culprit: systemd OR Xorg OR the display manager OR the desktop environment OR all of them. If you like you can start reading [here](https://unix.stackexchange.com/questions/122590/graceful-shutdown-in-archlinux) or [here](https://bugzilla.redhat.com/show_bug.cgi?id=1141137)
