### ISSUE TITLE
feature request bot api

### ISSUE THREAD

**Issue by freddii** [kontalk/desktopclient-java#69]
It would be nice to have an api so you can send commands to a bot or ask the bot things.

**Comment by abika** [comment]
What exactly do you need? A library so you can use the client for sending/receiving messages (like libpurple), or an IPC mechanism? A simple CLI would also be an option.

**Comment by freddii** [comment]
i want to run kontalk on a server. and i want the server to run the command i send to it from kontalk app. for example i send the server the message "logs" and then the server paste me some logfiles. 
thanks for your suggestions. i will try it with libpurple.

**Comment by daniele-athome** [comment]
I think a more appropriate way to do this is write an XMPP bot that connects to the Kontalk server and can be added by other people as a contact. There is no actual need for a XMPP server (unless you meant a server to run the XMPP bot client that is). Am I understanding your need right?

**Comment by freddii** [comment]
Yes just a xmpp bot client that connects to the kontalk  server an can be added by others as a contact.

**Comment by daniele-athome** [comment]
I don't think such a feature would be nicely incorporated in a desktop client... I think this is a job for an automated headless client, with its own configuration and automated replies and all of that. @abika what do you think?
@freddii are you a developer? Would you implement such a client yourself?

**Comment by freddii** [comment]
I am not a developer. I don't think i will be able to build a headless client myself. Just asking if such a client will be developed in future.

**Comment by abika** [comment]
The crucial point here is that there are already plenty XMPP bots for that purpose. They cannot connect to a Kontalk server (maybe with extension or modification) but instead use a standard XMPP account/server and Kontalk users can chat with them. (adding XMPP accounts is implemented in the desktop client and planned for the Android client)

But this isn't related to the desktop client, Im closing this. If somebody thinks otherwise we can further discuss this here.

**Comment by daniele-athome** [comment]
Sure, other clients (even bots) can use the tunnel adapter scripts without modifications to the software (however I recommend using a bot with client certificate authentication so you won't even need the tunnel adapter script).
However, messages will always be delivered unencrypted because Kontalk current encryption implementation is custom and the new OpenPGP XEP has just been released as experimental, so clients (and bots) need time to implement it (if they ever decide to).

Anyway, @abika is right: this is not related to the desktop client. If you want to discuss about using an existing bot implementation with Kontalk, please write to one of our Google Groups (kontalk-devel or kontalk-users). Thanks!

**Comment by freddii** [comment]
i tryed kontalk with errbot and the bridge on a raspberrypi.
it is working, but i am still missing encryption.

https://fredfire1.wordpress.com/2016/06/18/install-kontalk-bot-errbot-on-rpi2-raspberrypi2/

**Comment by daniele-athome** [comment]
Nice tutorial, thanks! We'll soon implement the new OX/OX-IM XEP for encryption so it will be better supported by clients. I see errbot is written in Python, maybe someone is up to the task of developing Kontalk encryption for it? :-)

**Comment by freddii** [comment]
i wrote a little script to install errbot on a rpi2 for kontalk.
still missing encryption.
https://github.com/freddii/kontalkpi
