### ISSUE TITLE
Kontalk Stickers

### ISSUE THREAD

**Issue by tushar-bhatia** [kontalk/desktopclient-java#71]
Hello Guys,
First of all I must say you all have done a master piece of work. I have gone through your app and find quite amazing features in it. But all I want to integrate stickers in this app but didn't find a way to do that. Please assist me further in doing that. Hoping for a satisfactory response from your side ASAP.
Thank You.!!!

**Comment by daniele-athome** [comment]
Hello, I guess [bits of binary](http://xmpp.org/extensions/xep-0231.html) could be used for this purpose. @abika what do you think?

**Comment by daniele-athome** [comment]
Hello, I guess [bits of binary](http://xmpp.org/extensions/xep-0231.html) could be used for this purpose. @abika what do you think?

**Comment by abika** [comment]
ahhh... stickers, well I'm not really excited about that. But yes, BoB would be ideal for implementation. We already have it for attachment thumbnail previews. That wouldn't be hard.

Other question is where do the stickers come from?

**Comment by daniele-athome** [comment]
Actually I don't like them either, but you know... people like them. @abika it's not high priority anyway.

> Other question is where do the stickers come from?

That's a good question. Would someone be so kind to provide a starting set with a proper usage license?

**Comment by tushar-bhatia** [comment]
well m having the collection of stickers with me as a .png images. But i didnt know how to integrate it with the smack library becoz you guyz have integrated smack for emojicons,

**Comment by tushar-bhatia** [comment]
and what about stickerpipe....just have a look :+1: https://github.com/908Inc/stickerpipe-chat-sample

**Comment by tushar-bhatia** [comment]
you have integrated rokerheiu library
but i didnt know how to integrate the stickers with it....can I integrate stickerpipe with it

**Comment by daniele-athome** [comment]
They seem to provide a public API with direct access, so no need to contain the whole sets into the apk (which will probably greatly increase final apk size). @abika what do you think?

**Comment by tushar-bhatia** [comment]
I didn't know from where to start...guide me further...just give me basic idea...rest I'll handle......

**Comment by abika** [comment]
Stickerpipe has non-free content with some strange pricing model. Doesn't look good to me

**Comment by tushar-bhatia** [comment]
which method is called when a new message arrives in kontalk...I didnt find it...I thinking to implement my own way to integrate stickers...But I didnt find the point of execution of the program when a new message arrives..is that some broadcast receiver or some service....
Thank You

**Comment by tushar-bhatia** [comment]
What m thinking is that i just send a unique code of a particular sticker and at receiver end I just recognize the code and load the correponding sticker into listview....But main problem arrives is that i dont want balloon theme to be appear on sticker background....I don't know how to handle this situation....hoping for a satisfactory response from your side

**Comment by daniele-athome** [comment]
@tushar-bhatia you're talking about Android stuff, yet you opened an issue in the desktop client. Which one would you like to focus on?

Anyway, stickers are not handled by unicode (like emojis), so using a code is not really an option here. Either:

* send the whole image with the stanza
* send a URL to the image in the stanza

The first option makes the image always be transmitted with the message; despite how small images could be, all stickers would be added to the apk which will grow a lot - unless we make a different package, maybe a plugin system of some kind (actually I was thinking of making it a separately sold add-on to support the project, but that's another story and not for the moment anyway), but it will complicate things a lot right now in a delicate phase that is group chat development.

The second option requires a HTTP service somewhere for hosting those common resources, such as that Stickerpipe, but it's non-free, so I guess we can't really use it, not without strings attached anyway (or without maybe reselling them).

As for the non-balloon shape, there is a pending issue for that in the Android repository, but I can't really give hints on that because I didn't research on it yet and don't really know how to do it. We'll be grateful though if you could do that research and integrate the feature yourself with a pull request, that'll be a great start! :-)

**Comment by tushar-bhatia** [comment]
Hey @daniele-athome i agree with you but the problem in sending a sticker as a complerte binary message is that it will behave as if we have sent a message with Image component just like other normal images...Now at the receiver end the user will have to download the sticker or let suppose it get automatically downloaded then it will get shown by the gallery app of the phone which is not required at this point of time.....What you think..????

One more thing i wanna ask you is that I didnt find a method in which your app has populated the conversation listview from incomming message....I found a class MessageListener which receives the incomming stanza...but didnt find where is the listview poulated by this packer

**Comment by daniele-athome** [comment]
> Hey @daniele-athome i agree with you but the problem in sending a sticker as a complete binary message is that it will behave as if we have sent a message with Image component just like other normal images...Now at the receiver end the user will have to download the sticker or let suppose it get automatically downloaded then it will get shown by the gallery app of the phone which is not required at this point of time.....What you think..????

I think in this special case they should be downloaded in the internal app cache automatically I guess.

> One more thing i wanna ask you is that I didnt find a method in which your app has populated the conversation listview from incomming message....I found a class MessageListener which receives the incomming stanza...but didnt find where is the listview poulated by this packet

Please let's continue this discussion on either the androidclient repo (it's OT here) or in the kontalk-devel group (even better, since the requirement is clear).

**Comment by abika** [comment]
No stickers right now. Still need a source with proper license.
